### ISSUE TITLE
32_Chart_read_write.php corrupted Excel 2013 file wth chart "xl/drawings/drawing1.xml"

### ISSUE THREAD

**Issue by DenisDT** [PHPOffice/PhpSpreadsheet#1767]
This is:

```
- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)
```
I try to copy .xlsx file with chart and insert data to this file for this chart. Tried different ways and still when file is saved, I can't open it successfully because it's corrupted. How can I fix it?

### What is the expected behavior?
Successfully save and open new .xlsx file with my data and chart

### What is the current behavior?

The error that Component "xl/drawings/drawing1.xml" is deleted.
Don't understand why my chart became drawing. 

### What are the steps to reproduce?

I have tried to reproduce the process with the help of ready sample.
[Sample/32_Chart_read_write.php](https://github.com/PHPOffice/PhpSpreadsheet/blob/master/samples/Chart/32_Chart_read_write.php)

Even with this sample, I can't save not corrupted file with chart.

```php
All code I have from "32_Chart_read_write.php" sample and used 2 my test.xlsx files that contain some date and 1 chart, 
```

**Comment by machour** [comment]
I can confirm that charts generation seems to be broken.
In my case, simply doing this gets a corrupted Xlsx file.
If I force open it, the chart is gone.

```php
$reader = IOFactory::createReader('Xlsx');
$reader->setIncludeCharts(true);
$spreadsheet = $reader->load('file_with_a_chart.xlsx');

$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->setIncludeCharts(true);
$writer->save('test.xlsx');
```

**Comment by oleibman** [comment]
Using 32readwriteAreaChart1.xlsx, which is created by the script DenisDT mentions, and running it with the code supplied by machour, I am not able to duplicate the error - my output file is uncorrupted and as expected, including the chart. What version of PhpSpreadsheet and PHP? Is there another file you think might trigger this problem?

**Comment by DenisDT** [comment]
> Using 32readwriteAreaChart1.xlsx, which is created by the script DenisDT mentions, and running it with the code supplied by machour, I am not able to duplicate the error - my output file is uncorrupted and as expected, including the chart. What version of PhpSpreadsheet and PHP? Is there another file you think might trigger this problem?

Working with another project with PHPWord and PHPSpreadsheet, I have noticed that my main problem of corrupting files was outputting some information before the file saving. 
`ob_clean();` helped me to solve this problem. 

I didn't tried this with charts so can't say helps it or not. I will try to test saving charts with ob_clean in my case, but can't say when it will be. 

In any case, thanks for your answer oleibman!

**Comment by bbinotto** [comment]
I can confirm that loading an xlsx which contains a chart, do some simple modifications (not to the chart) and saving it, generates a corrupted Xlsx file.

**Comment by bbinotto** [comment]
> I can confirm that loading an xlsx which contains a chart, do some simple modifications (not to the chart) and saving it, generates a corrupted Xlsx file.
> PhpSpreadsheet 1.17.1
> php 7.4.13
> File attached to this comment:
> [simplified2.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/6089906/simplified2.xlsx)

Interestingly: This only happens if there are more than one sheet!

**Comment by oleibman** [comment]
Yes, I can definitely duplicate your problem with the new downloaded file. I have a partial explanation for the problem, but am not close to a solution at the moment. The uploaded file is saved with 6 "shape" image files named vmlDrawing1.vml, where the digit ranges from 1 to 6. These are saved in directory xl/drawings in the xlsx file (which is basically a zipped version of a number of xml files). Also in that directory is a file called _rels, which has entries corresponding to 3 of the files - vmlDrawing2/4/6.vml.rels. When PhpSpreadsheet saves the file, it saves all the vml files (although 5 is renamed to HF3 for some reason), the _rels directory contains a file only HF3. When Excel reads this file, it "knows" that vmlDrawing2.vml should have a corresponding rels file, and, when it doesn't find one ... So the problem could be something like that the read routine needs to save all the rels files, or maybe it drops rels files which it thinks are unused but doesn't drop the corresponding vml file.

**Comment by rkyoku** [comment]
**I experience the same error.** I have 4 sheets, two charts on one of them.

The second chart (radar) seems to be the issue (it also fails if I replace the chart type "radar" by "bar").

- LibreOffice opens the file and displays the two charts (but seems to "modify" it because it is asking if I wish to save the changes, just after opening it ==> saving the file fixes it, and therefore it will open fine in MS Office afterwards).
- Zoho opens the file and displays the two charts (but it show values labels on the second chart, and not on the first chart, whereas it should be the other way around... bah, doesn't matter much).
- Excel Online opens the file but does not display any chart and tells me that there is an error in "drawing2.xml".
- Same with MS Office 2019
- iPhone "Pages" opens the file but only displays the first chart
- Google Sheets opens the file and displays both charts (but it does not display the values labels of chart1, and it does not display the legend labels of chart2)

More specifically, it is caused by this part of drawing2.xml: (because if I remove the second chart, which XML is below, it works fine)

```xml
  <xdr:twoCellAnchor>
    <xdr:from>
      <xdr:col>4</xdr:col>
      <xdr:colOff>0</xdr:colOff>
      <xdr:row>21</xdr:row>
      <xdr:rowOff>0</xdr:rowOff>
    </xdr:from>
    <xdr:to>
      <xdr:col>11</xdr:col>
      <xdr:colOff>95250</xdr:colOff>
      <xdr:row>35</xdr:row>
      <xdr:rowOff>95250</xdr:rowOff>
    </xdr:to>
    <xdr:graphicFrame macro="">
      <xdr:nvGraphicFramePr>
        <xdr:cNvPr name="Chart 2" id="2050"/>
        <xdr:cNvGraphicFramePr>
          <a:graphicFrameLocks/>
        </xdr:cNvGraphicFramePr>
      </xdr:nvGraphicFramePr>
      <xdr:xfrm>
        <a:off x="0" y="0"/>
        <a:ext cx="0" cy="0"/>
      </xdr:xfrm>
      <a:graphic>
        <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart">
          <c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:id="rId2"/>
        </a:graphicData>
      </a:graphic>
    </xdr:graphicFrame>
    <xdr:clientData/>
  </xdr:twoCellAnchor>
```

Here is the chart it is referring to (presumably the one with the error):

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <c:date1904 val="0"/>
  <c:lang val="en-GB"/>
  <c:roundedCorners val="0"/>
  <mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006">
    <mc:Choice xmlns:c14="http://schemas.microsoft.com/office/drawing/2007/8/2/chart" Requires="c14">
      <c14:style val="102"/>
    </mc:Choice>
    <mc:Fallback>
      <c:style val="2"/>
    </mc:Fallback>
  </mc:AlternateContent>
  <c:chart>
    <c:title>
      <c:tx>
        <c:rich>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:r>
              <a:rPr b="0" i="0" u="none" strike="noStrike">
                <a:latin typeface="Calibri"/>
              </a:rPr>
              <a:t>Domaines</a:t>
            </a:r>
          </a:p>
        </c:rich>
      </c:tx>
      <c:layout/>
      <c:overlay val="0"/>
    </c:title>
    <c:autoTitleDeleted val="0"/>
    <c:plotArea>
      <c:layout>
        <c:manualLayout/>
      </c:layout>
      <c:radarChart>
        <c:radarStyle val=""/>
        <c:grouping val="standard"/>
        <c:ser>
          <c:idx val="0"/>
          <c:order val="0"/>
          <c:tx>
            <c:strRef>
              <c:f>Statistiques!$B$1</c:f>
              <c:strCache>
                <c:ptCount val="1"/>
                <c:pt idx="0">
                  <c:v>Présentations</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:tx>
          <c:cat>
            <c:strRef>
              <c:f>Statistiques!$A$2:$A$11</c:f>
              <c:strCache>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>Arts</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>Botanique</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>Géographie</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>Géométrie</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>Langage</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>Mathématiques</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>Musique</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>Sciences</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>Sensoriel</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>Vie pratique</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:cat>
          <c:val>
            <c:numRef>
              <c:f>Statistiques!$C$2:$C$11</c:f>
              <c:numCache>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>0,0357</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>0,0357</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>0,0357</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>0,0357</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>0,8214</c:v>
                </c:pt>
              </c:numCache>
            </c:numRef>
          </c:val>
        </c:ser>
        <c:ser>
          <c:idx val="1"/>
          <c:order val="1"/>
          <c:tx>
            <c:strRef>
              <c:f>Statistiques!$D$1</c:f>
              <c:strCache>
                <c:ptCount val="1"/>
                <c:pt idx="0">
                  <c:v>Travail Autonome</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:tx>
          <c:cat>
            <c:strRef>
              <c:f>Statistiques!$A$2:$A$11</c:f>
              <c:strCache>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>Arts</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>Botanique</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>Géographie</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>Géométrie</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>Langage</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>Mathématiques</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>Musique</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>Sciences</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>Sensoriel</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>Vie pratique</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:cat>
          <c:val>
            <c:numRef>
              <c:f>Statistiques!$E$2:$E$11</c:f>
              <c:numCache>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>0,5</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>0,5</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>0</c:v>
                </c:pt>
              </c:numCache>
            </c:numRef>
          </c:val>
        </c:ser>
        <c:dLbls>
          <c:showLegendKey val="0"/>
          <c:showVal val="0"/>
          <c:showCatName val="0"/>
          <c:showSerName val="0"/>
          <c:showPercent val="0"/>
          <c:showBubbleSize val="0"/>
          <c:showLeaderLines val="0"/>
        </c:dLbls>
        <c:axId val="75091328"/>
        <c:axId val="75089408"/>
      </c:radarChart>
      <c:catAx>
        <c:axId val="75091328"/>
        <c:scaling>
          <c:orientation val="minMax"/>
        </c:scaling>
        <c:delete val="0"/>
        <c:axPos val="b"/>
        <c:numFmt formatCode="General" sourceLinked="1"/>
        <c:majorTickMark val="none"/>
        <c:minorTickMark val="none"/>
        <c:tickLblPos val="nextTo"/>
        <c:crossAx val="75089408"/>
        <c:crosses val="autoZero"/>
        <c:auto val="1"/>
        <c:lblAlgn val="ctr"/>
        <c:lblOffset val="100"/>
      </c:catAx>
      <c:valAx>
        <c:axId val="75089408"/>
        <c:scaling>
          <c:orientation val="minMax"/>
        </c:scaling>
        <c:delete val="0"/>
        <c:axPos val="l"/>
        <c:majorGridlines>
          <c:spPr>
            <a:effectLst/>
          </c:spPr>
        </c:majorGridlines>
        <c:numFmt formatCode="General" sourceLinked="1"/>
        <c:majorTickMark val="none"/>
        <c:minorTickMark val="none"/>
        <c:tickLblPos val="none"/>
        <c:spPr>
          <a:ln w="9525" cap="flat" cmpd="sng">
            <a:prstDash val="solid"/>
            <a:bevel/>
          </a:ln>
          <a:effectLst/>
        </c:spPr>
        <c:crossAx val="75089408"/>
        <c:crosses val="autoZero"/>
        <c:crossBetween val="midCat"/>
      </c:valAx>
    </c:plotArea>
    <c:legend>
      <c:legendPos val="r"/>
      <c:layout/>
      <c:overlay val="0"/>
      <c:txPr>
        <a:bodyPr/>
        <a:lstStyle/>
        <a:p>
          <a:pPr rtl="0">
            <a:defRPr/>
          </a:pPr>
          <a:endParaRPr lang="en-US"/>
        </a:p>
      </c:txPr>
    </c:legend>
    <c:plotVisOnly val="1"/>
    <c:dispBlanksAs val="0"/>
    <c:showDLblsOverMax val="0"/>
  </c:chart>
  <c:printSettings>
    <c:headerFooter/>
    <c:pageMargins footer="0,3" header="0,3" r="0,7" l="0,7" t="0,75" b="0,75"/>
    <c:pageSetup orientation="portrait"/>
  </c:printSettings>
</c:chartSpace>
```

Here is the file fixed by LibreOffice:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <c:lang val="en-US"/>
  <c:roundedCorners val="0"/>
  <c:chart>
    <c:title>
      <c:tx>
        <c:rich>
          <a:bodyPr rot="0"/>
          <a:lstStyle/>
          <a:p>
            <a:pPr>
              <a:defRPr b="0" sz="1800" spc="-1" strike="noStrike">
                <a:solidFill>
                  <a:srgbClr val="000000"/>
                </a:solidFill>
                <a:latin typeface="Calibri"/>
              </a:defRPr>
            </a:pPr>
            <a:r>
              <a:rPr b="0" sz="1800" spc="-1" strike="noStrike">
                <a:solidFill>
                  <a:srgbClr val="000000"/>
                </a:solidFill>
                <a:latin typeface="Calibri"/>
              </a:rPr>
              <a:t>Domaines</a:t>
            </a:r>
          </a:p>
        </c:rich>
      </c:tx>
      <c:overlay val="0"/>
      <c:spPr>
        <a:noFill/>
        <a:ln w="0">
          <a:noFill/>
        </a:ln>
      </c:spPr>
    </c:title>
    <c:autoTitleDeleted val="0"/>
    <c:plotArea>
      <c:radarChart>
        <c:radarStyle val="marker"/>
        <c:varyColors val="0"/>
        <c:ser>
          <c:idx val="0"/>
          <c:order val="0"/>
          <c:tx>
            <c:strRef>
              <c:f>Statistiques!$B$1:$B$1</c:f>
              <c:strCache>
                <c:ptCount val="1"/>
                <c:pt idx="0">
                  <c:v>Présentations</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:tx>
          <c:spPr>
            <a:solidFill>
              <a:srgbClr val="4a7ebb"/>
            </a:solidFill>
            <a:ln w="28440">
              <a:solidFill>
                <a:srgbClr val="4a7ebb"/>
              </a:solidFill>
              <a:round/>
            </a:ln>
          </c:spPr>
          <c:dLbls>
            <c:txPr>
              <a:bodyPr wrap="square"/>
              <a:lstStyle/>
              <a:p>
                <a:pPr>
                  <a:defRPr b="0" sz="1000" spc="-1" strike="noStrike">
                    <a:solidFill>
                      <a:srgbClr val="000000"/>
                    </a:solidFill>
                    <a:latin typeface="Calibri"/>
                  </a:defRPr>
                </a:pPr>
              </a:p>
            </c:txPr>
            <c:showLegendKey val="0"/>
            <c:showVal val="0"/>
            <c:showCatName val="0"/>
            <c:showSerName val="0"/>
            <c:showPercent val="0"/>
            <c:separator>; </c:separator>
            <c:showLeaderLines val="0"/>
            <c:extLst>
              <c:ext xmlns:c15="http://schemas.microsoft.com/office/drawing/2012/chart" uri="{CE6537A1-D6FC-4f65-9D91-7224C49458BB}">
                <c15:showLeaderLines val="0"/>
              </c:ext>
            </c:extLst>
          </c:dLbls>
          <c:cat>
            <c:strRef>
              <c:f>Statistiques!$A$2:$A$11</c:f>
              <c:strCache>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>Arts</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>Botanique</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>Géographie</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>Géométrie</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>Langage</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>Mathématiques</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>Musique</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>Sciences</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>Sensoriel</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>Vie pratique</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:cat>
          <c:val>
            <c:numRef>
              <c:f>Statistiques!$C$2:$C$11</c:f>
              <c:numCache>
                <c:formatCode>General</c:formatCode>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>0.0357</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>0.0357</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>0.0357</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>0.0357</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>0.8214</c:v>
                </c:pt>
              </c:numCache>
            </c:numRef>
          </c:val>
        </c:ser>
        <c:ser>
          <c:idx val="1"/>
          <c:order val="1"/>
          <c:tx>
            <c:strRef>
              <c:f>Statistiques!$D$1:$D$1</c:f>
              <c:strCache>
                <c:ptCount val="1"/>
                <c:pt idx="0">
                  <c:v>Travail Autonome</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:tx>
          <c:spPr>
            <a:solidFill>
              <a:srgbClr val="be4b48"/>
            </a:solidFill>
            <a:ln w="28440">
              <a:solidFill>
                <a:srgbClr val="be4b48"/>
              </a:solidFill>
              <a:round/>
            </a:ln>
          </c:spPr>
          <c:dLbls>
            <c:txPr>
              <a:bodyPr wrap="square"/>
              <a:lstStyle/>
              <a:p>
                <a:pPr>
                  <a:defRPr b="0" sz="1000" spc="-1" strike="noStrike">
                    <a:solidFill>
                      <a:srgbClr val="000000"/>
                    </a:solidFill>
                    <a:latin typeface="Calibri"/>
                  </a:defRPr>
                </a:pPr>
              </a:p>
            </c:txPr>
            <c:showLegendKey val="0"/>
            <c:showVal val="0"/>
            <c:showCatName val="0"/>
            <c:showSerName val="0"/>
            <c:showPercent val="0"/>
            <c:separator>; </c:separator>
            <c:showLeaderLines val="0"/>
            <c:extLst>
              <c:ext xmlns:c15="http://schemas.microsoft.com/office/drawing/2012/chart" uri="{CE6537A1-D6FC-4f65-9D91-7224C49458BB}">
                <c15:showLeaderLines val="0"/>
              </c:ext>
            </c:extLst>
          </c:dLbls>
          <c:cat>
            <c:strRef>
              <c:f>Statistiques!$A$2:$A$11</c:f>
              <c:strCache>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>Arts</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>Botanique</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>Géographie</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>Géométrie</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>Langage</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>Mathématiques</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>Musique</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>Sciences</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>Sensoriel</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>Vie pratique</c:v>
                </c:pt>
              </c:strCache>
            </c:strRef>
          </c:cat>
          <c:val>
            <c:numRef>
              <c:f>Statistiques!$E$2:$E$11</c:f>
              <c:numCache>
                <c:formatCode>General</c:formatCode>
                <c:ptCount val="10"/>
                <c:pt idx="0">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="1">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="2">
                  <c:v>0.5</c:v>
                </c:pt>
                <c:pt idx="3">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="4">
                  <c:v>0.5</c:v>
                </c:pt>
                <c:pt idx="5">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="6">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="7">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="8">
                  <c:v>0</c:v>
                </c:pt>
                <c:pt idx="9">
                  <c:v>0</c:v>
                </c:pt>
              </c:numCache>
            </c:numRef>
          </c:val>
        </c:ser>
        <c:axId val="40096947"/>
        <c:axId val="58322708"/>
      </c:radarChart>
      <c:catAx>
        <c:axId val="40096947"/>
        <c:scaling>
          <c:orientation val="maxMin"/>
        </c:scaling>
        <c:delete val="0"/>
        <c:axPos val="b"/>
        <c:numFmt formatCode="General" sourceLinked="0"/>
        <c:majorTickMark val="none"/>
        <c:minorTickMark val="none"/>
        <c:tickLblPos val="nextTo"/>
        <c:spPr>
          <a:ln w="9360">
            <a:noFill/>
          </a:ln>
        </c:spPr>
        <c:txPr>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:pPr>
              <a:defRPr b="0" sz="1000" spc="-1" strike="noStrike">
                <a:solidFill>
                  <a:srgbClr val="000000"/>
                </a:solidFill>
                <a:latin typeface="Calibri"/>
              </a:defRPr>
            </a:pPr>
          </a:p>
        </c:txPr>
        <c:crossAx val="58322708"/>
        <c:crosses val="autoZero"/>
        <c:auto val="1"/>
        <c:lblAlgn val="ctr"/>
        <c:lblOffset val="100"/>
        <c:noMultiLvlLbl val="0"/>
      </c:catAx>
      <c:valAx>
        <c:axId val="58322708"/>
        <c:scaling>
          <c:orientation val="minMax"/>
        </c:scaling>
        <c:delete val="0"/>
        <c:axPos val="l"/>
        <c:majorGridlines>
          <c:spPr>
            <a:ln w="9360">
              <a:solidFill>
                <a:srgbClr val="878787"/>
              </a:solidFill>
              <a:round/>
            </a:ln>
          </c:spPr>
        </c:majorGridlines>
        <c:numFmt formatCode="General" sourceLinked="0"/>
        <c:majorTickMark val="none"/>
        <c:minorTickMark val="none"/>
        <c:tickLblPos val="none"/>
        <c:spPr>
          <a:ln w="9360">
            <a:solidFill>
              <a:srgbClr val="878787"/>
            </a:solidFill>
            <a:round/>
          </a:ln>
        </c:spPr>
        <c:txPr>
          <a:bodyPr/>
          <a:lstStyle/>
          <a:p>
            <a:pPr>
              <a:defRPr b="0" sz="1000" spc="-1" strike="noStrike">
                <a:solidFill>
                  <a:srgbClr val="000000"/>
                </a:solidFill>
                <a:latin typeface="Calibri"/>
              </a:defRPr>
            </a:pPr>
          </a:p>
        </c:txPr>
        <c:crossAx val="40096947"/>
        <c:crosses val="autoZero"/>
        <c:crossBetween val="midCat"/>
      </c:valAx>
      <c:spPr>
        <a:noFill/>
        <a:ln w="0">
          <a:noFill/>
        </a:ln>
      </c:spPr>
    </c:plotArea>
    <c:legend>
      <c:legendPos val="r"/>
      <c:overlay val="0"/>
      <c:spPr>
        <a:noFill/>
        <a:ln w="0">
          <a:noFill/>
        </a:ln>
      </c:spPr>
      <c:txPr>
        <a:bodyPr/>
        <a:lstStyle/>
        <a:p>
          <a:pPr>
            <a:defRPr b="0" sz="1000" spc="-1" strike="noStrike">
              <a:solidFill>
                <a:srgbClr val="000000"/>
              </a:solidFill>
              <a:latin typeface="Calibri"/>
            </a:defRPr>
          </a:pPr>
        </a:p>
      </c:txPr>
    </c:legend>
    <c:plotVisOnly val="1"/>
    <c:dispBlanksAs val="gap"/>
  </c:chart>
  <c:spPr>
    <a:solidFill>
      <a:srgbClr val="ffffff"/>
    </a:solidFill>
    <a:ln w="9360">
      <a:solidFill>
        <a:srgbClr val="d9d9d9"/>
      </a:solidFill>
      <a:round/>
    </a:ln>
  </c:spPr>
</c:chartSpace>
```

Should you need anything else, please advise.

**Comment by rkyoku** [comment]
@oleibman have you come close to a solution by now, or would you have any advice on how to bypass this bug?

I am getting a lot of complaints from users, but I am not sure what I could do to help.

Please advise, I'd be glad to help you!

Best,

**Comment by oleibman** [comment]
I have no ideas at the moment. The module where this problem lies is particularly daunting. I am working on it for a different reason right now. My hope is that that work will give greater insight to addressing this. At any rate, I haven't given up on it.

**Comment by oleibman** [comment]
Bad news. I confirmed that rels wasn't being captured during read, added some code to capture it and write it, and then found that the actual vml file was being overlaid. This doesn't appear to have been the case before, but it appears to happen even with an unchanged master now. I think I know which change did that, but it doesn't matter, because I stopped the overlay from happening ... and then discovered that image1.png from the original is image11.png in the new. So I manually changed that, but Excel still objected to a shape file, and now a comments file as well. So I'm not even sure I'm closer to a solution than I was. If I can't figure out what is needed manually, I may not be able to proceed at all.

**Comment by oleibman** [comment]
Sorry, I only know what change caused the file to be overlaid. I don't know a version where the whole thing actually worked.

**Comment by rkyoku** [comment]
I am sorry, I tried like a dozen versions, even down to `1.3.0` (3 years ago).

When the version gets too old, there are a few issues of "array access" in a few files. That I fixed. But there still is the charts bug.

As far as I know, then, the bug always existed.

How come we are only 3 or 4 people to notice it? Even with the official examples from the documentation.

Maybe it only happens in certain conditions... My country is France, maybe it's a locale issue (but a locale issue related to charts... it seems unlikely)

**Comment by rkyoku** [comment]
@oleibman **I could fix it** by changing only 2 lines in `chart1.xml`!

## Manual fix in chart.xml

Before:
```xml
<c:dispBlanksAs val="0"/>
<c:pageMargins footer="0,3" header="0,3" r="0,7" l="0,7" t="0,75" b="0,75"/>
```

After:
```xml
<c:dispBlanksAs val="zero"/>
<c:pageMargins b="0" l="0" r="0" t="0" header="0" footer="0"/>
```

With this, it works fine (I checked again from scratch just to be sure).

With your knowledge, do you understand why it would cause a bug?
(as for the margins, I could understand that this may indeed be a locale issue as I thought earlier, but why isn't `0` accepted as blank val?)

## Attempt to fix using PhpSpreadsheet API

### dispBlanksAs

I found how to change the blank val, in the chart constructor, and it has the desired effect on the resulting chart1.xml

### pageMargins

However, regarding the margins, I tried to call:

```php
$worksheet->getPageMargins()
      ->setTop(0)
      ->setRight(0)
      ->setLeft(0)
      ->setBottom(0)
      ->setHeader(0)
      ->setFooter(0)
;
```

But it doesn't seem to have any effect, the margins in the chart remain unchanged (`footer="0,3" header="0,3" r="0,7" l="0,7" t="0,75" b="0,75"`)

Maybe it's because I did set the sheet margins and not the chart margins?

After a quick look, I did not find how to change the chart margins.

**==> Do you have any idea** @oleibman ?

## Source code for the sample bugged file

Here is the full source code for generating a sample bugged file (from the official examples, except I removed one of the two charts):

```php
public function testxls1()
{
	$spreadsheet = new Spreadsheet();
	$worksheet = $spreadsheet->getActiveSheet();
	$worksheet->fromArray(
		[
			['', '2010', '2011', '2012'],
			['Q1', '12', '15', '21'],
			['Q2', '56', '73', '86'],
			['Q3', '52', '61', '69'],
			['Q4', '30', '32', '0'],
		]
	);

	$dataSeriesLabels1 = [
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$B$1', null, 1), // 2010
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$C$1', null, 1), // 2011
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$D$1', null, 1), // 2012
	];
	$xAxisTickValues1 = [
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_STRING, 'Worksheet!$A$2:$A$5', null, 4), // Q1 to Q4
	];
	$dataSeriesValues1 = [
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$B$2:$B$5', null, 4),
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$C$2:$C$5', null, 4),
		new DataSeriesValues(DataSeriesValues::DATASERIES_TYPE_NUMBER, 'Worksheet!$D$2:$D$5', null, 4),
	];

	$series1 = new DataSeries(
		DataSeries::TYPE_AREACHART, // plotType
		DataSeries::GROUPING_PERCENT_STACKED, // plotGrouping
		range(0, count($dataSeriesValues1) - 1), // plotOrder
		$dataSeriesLabels1, // plotLabel
		$xAxisTickValues1, // plotCategory
		$dataSeriesValues1          // plotValues
	);

	$plotArea1 = new PlotArea(null, [$series1]);
	$legend1 = new Legend(Legend::POSITION_TOPRIGHT, null, false);

	$title1 = new Title('Test %age-Stacked Area Chart');
	$yAxisLabel1 = new Title('Value ($k)');

	$chart1 = new Chart(
		'chart1', // name
		$title1, // title
		$legend1, // legend
		$plotArea1, // plotArea
		true, // plotVisibleOnly
		'0', // displayBlanksAs
		null, // xAxisLabel
		$yAxisLabel1 // yAxisLabel
	);

	$chart1->setTopLeftPosition('A7');
	$chart1->setBottomRightPosition('H20');

	$worksheet->addChart($chart1);

	$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
	$writer->setIncludeCharts(true);
	$writer->save('tmp1.xlsx');

	die();
}
```

Hope this helps!

**Comment by rkyoku** [comment]
@oleibman for the pageMargins, the values seem to be hardcoded in `src/PhpSpreadsheet/Writer/Xlsx/Chart.php` line `1502`:

```php
$objWriter->startElement('c:pageMargins');
$objWriter->writeAttribute('footer', 0.3);
$objWriter->writeAttribute('header', 0.3);
$objWriter->writeAttribute('r', 0.7);
$objWriter->writeAttribute('l', 0.7);
$objWriter->writeAttribute('t', 0.75);
$objWriter->writeAttribute('b', 0.75);
$objWriter->endElement();
```

And I'm pretty sure the writer uses some config about the locale my computer is in (`fr_FR`)
(I checked in the prod env, and it outputs `0.75`, which is fine, instead of `0,75` in my local env)

I'm afraid I can't do anything except cloning the repo, and it bothers me 😟

**Comment by rkyoku** [comment]
There is also another bug when using the `radar` chart type. I'll try to debug it.
(the `bar` chart works fine)

**Comment by rkyoku** [comment]
@oleibman found it!

In `chart1.xml`, this line must be removed:
```xml
<c:grouping val="standard"/>
```

It was caused by some code I made generic for creating different charts...
IMHO you should force grouping to be `null` in case of radar/pie/doughnut charts, otherwise it will break the resulting file.

Also, the line below must be changed from this...
```xml
<c:radarStyle val=""/>
```

... Into this:
```xml
<c:radarStyle val="marker"/>
```

The `radarStyle` issue comes from `src/PhpSpreadsheet/Writer/Xlsx/Chart.php` line `233`:
```php
// Combining several instructions here
$plotStyle = $plotArea->getPlotGroupByIndex($i)->getPlotType()->getPlotStyle();
// This line does the trick (line 233)
$objWriter->writeAttribute('val', $plotStyle);
```

I think it's because the default value is `null`. IMHO you should force a value of `marker` in case of radar chart, otherwise it breaks the resulting file.

Hope this helps!

**Comment by oleibman** [comment]
Please test against PR 2423 if possible. I know it handles at least some of the problems mentioned here; I'm not sure that it handles them all. I will probably leave the PR unmerged for a couple of weeks to allow for testing.

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/PHPOffice/PhpSpreadsheet/releases/tag/1.21.0

**Comment by bridgeplayr** [comment]
Issue #1893 is still present in phpspreadsheet version 1.22.0.  I have several template spreadsheets with scatter-charts which Excel complains about and removes.  [I use Excel for Microsoft 365 MSO (Version 2203).]

I have spent several weeks investigating this issue with little success, and have been following phpspreadsheet bug reports with interest.  I offer the following Chart observations from the samples/Chart which are easy to reproduce with no input required to download.  I hope these observations can help pinpoint deficient code by how it might cause these observed behaviors.  Symptoms of output chart alterations can be seen in subtle changes to the following template scatter charts:

In all output charts, the x-axis changes from 0-14 with no offset to 1-12 with offset.  The rich text font in the Chart Title is changed in all of the output charts.

input template: 32readwriteScatterChart1.xlsx - "No join and Markers"
output chart differences: points joined with lines; data point color changed from yellow to theme green
(line type changed from "No line" to "automatic"); 

input template: 32readwriteScatterChart2 - "Scatter - Join Bezier and Markers"
output chart differences; points joined with straight lines instead of Bezier curves.  

Input template: 32readwriteScatterChart3 - "Scatter - Join Straight Lines and Markers"
output chart differences; 

input template: 32readwriteScatterChart4 - "Scatter - Join Bezier and No Markers"
output chart differences; straight lines instead of Bezier curves

input template: 32readwriteScatterChart5 - "Scatter - Join Straight Lines No Markers"
output chart differences; no additional changes

It seems that the "Chart type" selection is munged (Chart1 specifically).  There seem to be many Chart Types, with sub-types, some of which affect the Plot Area and Theme, and some which affect the way data points are connected (or not connected at all).

I am delving into the underlying code in phpspreadsheet/Chart but I am groping in the dark without some specifications about the structure of Excel charts from Microsoft.

My spreadsheet with charts rejected by Excel : 
[4934180_Charts.xlsx](https://github.com/PHPOffice/PhpSpreadsheet/files/8517379/4934180_Charts.xlsx)

**Comment by oleibman** [comment]
@bridgeplayr Can you open the scatter chart samples problems that you've documented so well as a new issue. I think those problems are different from the file corruption issues.
